(() => {
  'use strict';
  const $=id=>document.getElementById(id), config=window.LPS_AUTH_CONFIG||{};
  const configured=/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(config.url||'')&&/^sb_publishable_/.test(config.publishableKey||'');
  let mode=new URLSearchParams(location.search).get('mode')||'login';
  if(!['login','register','recover','reset'].includes(mode))mode='login';
  let session=null;try{session=JSON.parse(sessionStorage.getItem('lps_session'))}catch{}
  function status(text){$('status').textContent=text}
  function remember(data){session={access_token:data.access_token,refresh_token:data.refresh_token,expires_at:Date.now()+(data.expires_in||3600)*1000};sessionStorage.setItem('lps_session',JSON.stringify(session))}
  async function request(path,body,method='POST',token){const res=await fetch(config.url+'/auth/v1'+path,{method,headers:{apikey:config.publishableKey,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(15000)});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.msg||data.error_description||data.message||'Could not complete this request. Please try again.');return data}
  async function token(){if(!session)throw new Error('Please log in again.');if(session.expires_at<Date.now()+60000)remember(await request('/token?grant_type=refresh_token',{refresh_token:session.refresh_token}));return session.access_token}
  function layout(){const register=mode==='register',recover=mode==='recover',reset=mode==='reset';$('heading').textContent=register?'Make room for possibility.':recover?'Reset your password.':reset?'Choose a new password.':'Welcome back.';$('intro').textContent=register?'Create your member account.':recover?'We’ll email you a secure reset link.':reset?'Enter a new password to complete recovery.':'Log in with your email and password.';$('submit').textContent=register?'Create account':recover?'Send reset link':reset?'Update password':'Log in';$('nameField').hidden=!register;$('fullName').required=register;$('emailField').hidden=reset;$('email').required=!reset;$('passwordField').hidden=recover;$('password').required=!recover;$('password').minLength=register||reset?12:1;$('password').autocomplete=register||reset?'new-password':'current-password';$('confirmField').hidden=!(register||reset);$('confirm').required=register||reset;$('forgot').hidden=recover||reset;$('loginTab').setAttribute('aria-current',mode==='login'?'page':'false');$('registerTab').setAttribute('aria-current',register?'page':'false')}
  layout();
  $('showPassword').onclick=()=>{const show=$('password').type==='password';$('password').type=show?'text':'password';$('showPassword').textContent=show?'Hide':'Show';$('showPassword').setAttribute('aria-label',show?'Hide password':'Show password')};
  async function showAccount(){const user=await request('/user',null,'GET',await token());$('userEmail').textContent='Signed in as '+user.email;$('authForm').hidden=true;$('forgot').hidden=true;$('signedIn').hidden=false;$('heading').textContent='You’re signed in.';$('intro').textContent='Welcome to LPS Project Studio.';status('')}
  if(!configured){$('fields').disabled=true;status('Member registration is not open yet. You can explore the portfolio and property preview while account access is being connected.');return}
  async function init(){const hash=new URLSearchParams(location.hash.slice(1));if(hash.has('access_token')){remember({access_token:hash.get('access_token'),refresh_token:hash.get('refresh_token'),expires_in:Number(hash.get('expires_in'))});mode=hash.get('type')==='recovery'?'reset':'login';history.replaceState(null,'',location.pathname+'?mode='+mode);layout()}
  if(mode==='reset'&&!session){$('fields').disabled=true;status('Open the secure password reset link from your email.');return}if(session&&mode!=='reset'){try{await showAccount()}catch{session=null;sessionStorage.removeItem('lps_session');status('Please log in to continue.')}}}
  init().catch(()=>status('Could not verify your session. Please log in again.'));
  $('authForm').onsubmit=async e=>{e.preventDefault();const email=$('email').value.trim(),password=$('password').value;if((mode==='register'||mode==='reset')&&password!==$('confirm').value){status('The passwords do not match.');$('confirm').focus();return}$('fields').disabled=true;status('Please wait…');try{if(mode==='register'){await request('/signup?redirect_to='+encodeURIComponent(location.origin+'/account/'),{email,password,data:{full_name:$('fullName').value.trim()}});status('Check your email to confirm your account, then log in.');$('authForm').reset()}else if(mode==='recover'){await request('/recover?redirect_to='+encodeURIComponent(location.origin+'/account/?mode=reset'),{email});status('If an account exists for this email, a reset link will arrive shortly.')}else if(mode==='reset'){await request('/user',{password},'PUT',await token());await showAccount();status('Your password has been updated.')}else{remember(await request('/token?grant_type=password',{email,password}));$('authForm').reset();await showAccount()}}catch(err){status(err.name==='TimeoutError'?'The request timed out. Please try again.':err.message)}finally{$('fields').disabled=false}};
  $('signOut').onclick=async()=>{try{await request('/logout',null,'POST',await token())}catch{}sessionStorage.removeItem('lps_session');location.href='/account/'};
})();
