const deals=[
{id:"PB-001",market:"Rockford, IL",type:"Single Family",strategy:"Assumable FHA",ask:145000,value:158000,loan:136400,rate:3.125,rent:1550,repairs:7000,score:88,confidence:"Estimated",signals:["Low equity gap","Rate under 4%","Rentable market"]},
{id:"PB-002",market:"Chicago, IL",type:"2-Flat",strategy:"Seller Financing",ask:165000,value:205000,loan:null,rate:null,rent:2450,repairs:22000,score:84,confidence:"Unknown",signals:["Long-hold owner","2 units","Seller-finance candidate"]},
{id:"PB-003",market:"Gary, IN",type:"Single Family",strategy:"Distressed",ask:79000,value:128000,loan:61200,rate:null,rent:1350,repairs:28000,score:74,confidence:"Estimated",signals:["Large spread","Rehab required","Title check"]},
{id:"PB-004",market:"Marion, AR",type:"Land",strategy:"Land + Modular",ask:24900,value:null,loan:null,rate:null,rent:null,repairs:null,score:69,confidence:"Unknown",signals:["Utilities nearby","Modular candidate","Zoning verify"]},
{id:"PB-005",market:"Peoria, IL",type:"Duplex",strategy:"Seller Financing",ask:119000,value:154000,loan:67000,rate:null,rent:2100,repairs:12000,score:90,confidence:"Estimated",signals:["Strong rent ratio","Owner equity","2 units"]},
{id:"PB-006",market:"South Bend, IN",type:"Single Family",strategy:"Assumable FHA",ask:179900,value:190000,loan:167500,rate:3.5,rent:1750,repairs:5000,score:86,confidence:"Estimated",signals:["Low rate","Small equity gap","Light repairs"]}
];
const $=s=>document.querySelector(s), money=n=>n==null?"Unknown":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
const read=(k)=>{try{return JSON.parse(localStorage.getItem(k))||[]}catch{return[]}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let saved=read("pbn_saved"),sellers=read("pbn_sellers"),buyers=read("pbn_buyers"),outreach=read("pbn_outreach");

function toast(msg){const t=document.createElement("div");t.className="toast";t.textContent=msg;document.body.append(t);setTimeout(()=>t.remove(),2200)}
function filtered(){const q=$("#q").value.toLowerCase(),s=$("#strategy").value,t=$("#ptype").value;return deals.filter(d=>(!q||JSON.stringify(d).toLowerCase().includes(q))&&(!s||d.strategy===s)&&(!t||d.type===t))}
function renderDeals(){const rows=filtered();$("#dealGrid").innerHTML=rows.map(d=>`
<article class="deal"><div class="deal-top"><span class="deal-type">${d.strategy}</span><span class="deal-score">${d.score}</span></div><div class="deal-body"><h3>${money(d.ask)}</h3><div class="sub">${d.type} • ${d.market}</div><div class="rows"><div class="row"><span>Est. value</span><b>${money(d.value)}</b></div><div class="row"><span>Est. loan</span><b>${money(d.loan)}</b></div><div class="row"><span>Rate</span><b>${d.rate?d.rate+"%":"Unknown"}</b></div><div class="row"><span>Est. rent</span><b>${money(d.rent)}</b></div><div class="row"><span>Repairs</span><b>${money(d.repairs)}</b></div></div><div class="badges"><span class="badge ${d.confidence.toLowerCase()}">${d.confidence}</span>${d.signals.slice(0,2).map(x=>'<span class="signal">'+x+'</span>').join("")}</div><div class="actions"><button class="btn small" onclick="openDNA('${d.id}')">Property DNA</button><button class="btn small" onclick="saveDeal('${d.id}')">Save</button><button class="btn small gold" onclick="queueOutreach('${d.id}')">Outreach Draft</button></div></div></article>`).join("")||"<p>No demo deals match.</p>"}
window.saveDeal=id=>{if(!saved.includes(id)){saved.push(id);write("pbn_saved",saved);toast("Deal saved")}updateStats()};
window.queueOutreach=id=>{const d=deals.find(x=>x.id===id);const draft={id:"OUT-"+Date.now(),deal:id,market:d.market,status:"Draft",text:`Hello, I'm reaching out regarding a property opportunity in ${d.market}. I'm interested in learning whether the owner would consider a sale and whether flexible terms such as seller financing or an assumable loan may be available. No obligation—I'd simply like to understand the property and the owner's goals.`};outreach.push(draft);write("pbn_outreach",outreach);renderOutreach();toast("Draft added — manual review required")};
window.openDNA=id=>{const d=deals.find(x=>x.id===id);$("#dnaAddress").value=d.market;$("#dnaResult").innerHTML=`<h4>${d.id} • ${d.market}</h4><div class="badges"><span class="badge estimated">ESTIMATED</span><span class="badge unknown">VERIFY TITLE / LOAN</span></div><div class="timeline"><div class="event"><b>History</b><span>Demo timeline placeholder for prior sale, refinance and listing events.</span></div><div class="event"><b>Equity</b><span>${d.loan&&d.value?money(d.value-d.loan)+" estimated gross equity":"Unknown until debt/value are verified"}.</span></div><div class="event"><b>Strategy</b><span>${d.strategy} is the current candidate path.</span></div></div><div class="signals">${d.signals.map(x=>'<span class="signal">'+x+'</span>').join("")}</div>`;document.querySelector("#dna").scrollIntoView({behavior:"smooth"})};

function analyzeDNA(){const address=$("#dnaAddress").value.trim();if(!address){toast("Enter an address");return}$("#dnaResult").innerHTML=`<h4>Property DNA request: ${address}</h4><div class="badges"><span class="badge unknown">LIVE DATA NOT CONNECTED</span></div><div class="timeline"><div class="event"><b>1</b><span>Ownership/deed history</span></div><div class="event"><b>2</b><span>Sales/listing history + price changes</span></div><div class="event"><b>3</b><span>Taxes, liens, mortgage indicators and distress</span></div><div class="event"><b>4</b><span>Zoning, permits, comps, rents and financing paths</span></div></div><p class="sub">This MVP shows the workflow only. Production APIs will populate verified and estimated fields separately.</p>`}

function scoreDeal(){
 const price=+$("#calcPrice").value||0,value=+$("#calcValue").value||0,loan=+$("#calcLoan").value||0,rent=+$("#calcRent").value||0,repairs=+$("#calcRepairs").value||0,monthly=+$("#calcMonthly").value||0;
 let score=50;
 if(value&&price){const discount=(value-price)/value;if(discount>.25)score+=18;else if(discount>.12)score+=10;else if(discount<0)score-=15}
 if(loan&&price){const gap=price-loan;if(gap<=10000)score+=12;else if(gap>30000)score-=7}
 if(rent&&monthly){const cushion=rent-monthly;if(cushion>500)score+=12;else if(cushion>200)score+=6;else if(cushion<0)score-=15}
 if(repairs&&value&&repairs/value>.3)score-=12;
 score=Math.max(0,Math.min(100,Math.round(score)));
 const path=loan&&price-loan<=15000?"Investigate assumption / low-equity purchase":value&&price<value*.75?"Investigate wholesale / value-add spread":rent&&monthly&&rent>monthly+300?"Investigate hold / rental financing":"Gather more verified data before choosing strategy";
 $("#scoreValue").textContent=score;$("#scoreRing").style.background=`conic-gradient(var(--green) 0deg ${score*3.6}deg,#17304a ${score*3.6}deg)`;$("#scoreSummary").innerHTML=`<b>${path}</b><p>Prototype score only. Verify title, debt, taxes, insurance, condition, rents, zoning and financing before committing funds.</p>`;
}

function calcMatches(){let count=0;sellers.forEach(s=>buyers.forEach(b=>{const price=+s.price||Infinity,max=+b.max||0,market=(b.market||"").toLowerCase();if(price<=max&&(!market||(s.market||"").toLowerCase().includes(market)))count++}));return count}
function updateStats(){$("#savedCount").textContent=saved.length;$("#sellerCount").textContent=sellers.length;$("#buyerCount").textContent=buyers.length;$("#matchCount").textContent=calcMatches();$("#outreachCount").textContent=outreach.length}
function renderCRM(){$("#sellerList").innerHTML=sellers.length?sellers.slice(-6).reverse().map(s=>`<div class="item"><strong>${s.address}</strong><small>${s.market} • ${s.need} • ${money(+s.price||0)}</small></div>`).join(""):"<div class='item'>No seller leads yet.</div>";$("#buyerList").innerHTML=buyers.length?buyers.slice(-6).reverse().map(b=>`<div class="item"><strong>${b.name}</strong><small>${b.market||"Any market"} • ${b.strategy} • max ${money(+b.max||0)}</small></div>`).join(""):"<div class='item'>No buyer profiles yet.</div>";$("#matchList").innerHTML=calcMatches()?sellers.flatMap(s=>buyers.filter(b=>(+s.price||Infinity)<=(+b.max||0)&&(!(b.market||"")||(s.market||"").toLowerCase().includes((b.market||"").toLowerCase()))).map(b=>`<div class="item match"><strong>${s.address} ↔ ${b.name}</strong><small>${s.market} • within buy box</small></div>`)).slice(0,8).join(""):"<div class='item'>No current matches.</div>"}
function renderOutreach(){$("#outreachList").innerHTML=outreach.length?outreach.slice(-5).reverse().map(o=>`<div class="item outreach"><strong>${o.deal} • ${o.market}</strong><small>${o.status} — manual review before sending</small><p class="sub">${o.text}</p></div>`).join(""):"<div class='item'>No outreach drafts yet.</div>";updateStats()}
function wireForms(){
 $("#sellerForm").onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));sellers.push(d);write("pbn_sellers",sellers);e.currentTarget.reset();renderCRM();updateStats();toast("Seller lead saved")};
 $("#buyerForm").onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));buyers.push(d);write("pbn_buyers",buyers);e.currentTarget.reset();renderCRM();updateStats();toast("Buyer profile saved")};
}
$("#q").oninput=renderDeals;$("#strategy").onchange=renderDeals;$("#ptype").onchange=renderDeals;$("#dnaAnalyze").onclick=analyzeDNA;$("#scoreBtn").onclick=scoreDeal;$("#clearData").onclick=()=>{if(confirm("Clear browser-only PROPERTYBridge demo data?")){["pbn_saved","pbn_sellers","pbn_buyers","pbn_outreach"].forEach(k=>localStorage.removeItem(k));saved=[];sellers=[];buyers=[];outreach=[];renderCRM();renderOutreach();updateStats();toast("Demo CRM cleared")}};
wireForms();renderDeals();renderCRM();renderOutreach();updateStats();scoreDeal();
